# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97895090786fc08a71165e4a165cb19b5fe4735451bca1ef695e00a6679b7946230e71df7025c209998a55f7f532f4273f19e5124e36215175836b25b4a89b88

test:
  secret_key_base: 2eee83c7401325c09473f1af07610ef184c8261567fb34b23c5bdfd970c94d1fd8c3517bbf43f3bd50e982e6cd309f120dd6cbadb08b98b97e8dabfeed856316

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
